# Simple workflow for deploying static content to GitHub Pages
name: Deploy to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
      - name: Install .NET Wasm Tools
        run: dotnet workload install wasm-tools
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish
        run: dotnet publish FinancesApp.csproj -c Release -o docs --no-logo
        
